on: [push]

name: build&test

jobs:
  build:
    name: test and build Manjaliof
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Test
        run: cargo test
      - name: Build
        run: cargo build --release

      - uses: actions/upload-artifact@v3
        with:
          name: manjaliof-bin
          path: target/release/manjaliof
